---
driver:
  name: vagrant
  region: us-west-1
  instance_type: t2.micro
  tags:
    Name: HTTP Platform
    Service: Infrastructure
    Environment: Test
    Fund: 103010
    Org: 60412
    Department: Systems Engineering

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_name: chef
  product_version: 14.10.9
  install_strategy: once
  attributes:
    se_baseline:
      chef_client_version: '14.8.12'
      configure_monitoring: false
    nix_baseline:
      chef_client_version: '14.8.12'
      configure_update: false
      hostname: 'funny.business'
    http_platform:
      admin_email: 'fake-it@make-it'
      apache:
        extra_mods_to_install:
          - 'lua'
        install_test_suite: true
      cert:
        organization: 'fake_org'
        org_unit: 'fake_unit'
      www:
        access_directories:
          /:
            - '/'
            - 'index.html'
          /stuff: ''
        additional_aliases:
          me.also:
            log_level: 'info'
        error_documents:
          '403': '403_puppy.php'
          '404': '404_kitten.php'
        redirect_rules:
          - comment: 'Site owners are a pain'
            from_regex: '/old_site'
            to_regex: '/new_site'
        rewrite_rules:
          - url_regex: '/url_of_page(.*)'
            path_regex: '/path_to_file$1'
            flags: '[L,NC]'
        remove_default_index: false
        create_default_index: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: debian-9
  - name: debian-8
  - name: centos-7
  - name: centos-6
  - name: oracle-7.6
  - name: oracle-6.10
  - name: fedora-29
  - name: fedora-28
  - name: bento/amazonlinux-2 # amazon2
  - name: realreadme/amazon2016.09 # amazon-
  - name: bento/opensuse-leap-15 # sles-15
  - name: StefanScherer/windows_2019 # windows-2019
    driver:
      image_id: ami-087efd22b572d6bc1
    transport:
      name: winrm
  - name: mwrock/Windows2016 # windows-2016
    transport:
      name: winrm
  - name: a-mcf/Win2012R2-WMF5-min # windows-2012r2
    transport:
      name: winrm
  - name: salesforce/server2008r2 # windows-2008r2sp1
    transport:
      name: winrm

suites:
  - name: self
    run_list:
      - recipe[se-nix-baseline::default]
      - recipe[http_platform::default]
    data_bags_path: "test/integration/data_bags"
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/self_signed_cert
    attributes:
    includes:
      - ubuntu-18.04
      - ubuntu-16.04
      - centos-7
  - name: vault
    run_list:
      - recipe[se-nix-baseline::default]
      - recipe[http_platform::default]
    data_bags_path: "test/integration/data_bags"
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/vault_cert
    attributes:
      http_platform:
        configure_vault_cert: true
        key:
          vault_item_key: 'key'
    includes:
      - ubuntu-18.04
      - ubuntu-16.04
      - centos-7
  - name: certbot
    run_list:
      - recipe[se-nix-baseline::default]
      - recipe[http_platform::default]
    data_bags_path: "test/integration/data_bags"
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/lets_encrypt_cert
    attributes:
      http_platform:
        configure_lets_encrypt_cert: true
        cert:
          kitchen_test: true
    includes:
      - ubuntu-18.04
      - ubuntu-16.04
      - centos-7
