---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_name: chef
  product_version: 15.4.45
  install_strategy: once
  attributes:
    firewall:
      allow_ssh: true
    http_platform:
      admin_email: 'ua-oit-se@alaska.edu' # Must appear valid for certbot
      apache:
        extra_mods_to_install:
          - 'lua'
        install_test_suite: true
      cert:
        organization: 'fake_org'
        org_unit: 'fake_unit'
      www:
        access_directories:
          /:
            - '/'
            - 'index.html'
          /stuff: ''
        error_documents:
          '403': '403_puppy.php'
          '404': '404_kitten.php'
        redirect_rules:
          - comment: 'Site owners are a pain'
            from_regex: '/old_site'
            to_regex: '/new_site'
        rewrite_rules:
          - url_regex: '/url_of_page(.*)'
            path_regex: '/path_to_file$1'
            flags: '[L,NC]'
        remove_default_index: false
        create_default_index: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: debian-9
  - name: rhel-8
  - name: centos-7
  - name: centos-6
  - name: oracle-7.6
  - name: oracle-6.10
  - name: fedora-30
  - name: fedora-29
  - name: amazon2
  - name: sles-15
    driver:
      image_search:
        owner-id: '013907871322'
        name: suse-sles-15*
  - name: windows-2019
  - name: windows-2016
  - name: windows-2012r2

suites:
  - name: self
    run_list:
      - recipe[chef_run_recorder::default]
      - recipe[test_harness::local]
    data_bags_path: 'test/integration/data_bags'
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/local_cert
        - test/integration/self_signed_cert
    attributes:
      http_platform:
        www:
          additional_aliases:
            me.also:
              log_level: 'info'
    includes:
      - ubuntu-18.04
  - name: vault
    run_list:
      - recipe[chef_run_recorder::default]
      - recipe[test_harness::local]
    data_bags_path: 'test/integration/data_bags'
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/local_cert
        - test/integration/vault_cert
    attributes:
      http_platform:
        configure_vault_cert: true
        key:
          vault_item_key: 'key'
        www:
          additional_aliases:
            me.also:
              log_level: 'info'
    includes:
      - centos-7
